### ISSUE TITLE
AttributeError: The 'credentials' param has been removed.

### ISSUE THREAD

**Issue by McKay1717** [mozilla-services/syncclient#23]
Hello,
I have problem with your script : 
nicolas@debian:~/syncclient# python syncclient/main.py $mail $pwd get_records passwords
Traceback (most recent call last):
  File "syncclient/main.py", line 27, in <module>
    main()
  File "syncclient/main.py", line 23, in main
    client = SyncClient(_bid_assertion_args)
  File "/root/syncclient/syncclient/client.py", line 107, in **init**
    'key': credentials['key']
  File "/usr/local/lib/python2.7/dist-packages/requests_hawk-1.0.0-py2.7.egg/requests_hawk/**init**.py", line 43, in **init**
    raise AttributeError("The 'credentials' param has been removed. "
AttributeError: The 'credentials' param has been removed. Pass 'id' and 'key' instead, or '_*credentials_dict

**Comment by Natim** [comment]
Thank you for noticing, I will have a look at it today.

**Comment by Natim** [comment]
Addressed in https://github.com/mozilla-services/syncclient/pull/24

**Comment by Natim** [comment]
Fixed in #24
